-- 0002_memory_model.sql — Unit 2 schema: entities, facts, events, relationships,
-- and the provenance index.
--
-- ADR-004: forward-only. Do not edit this file once applied; add a new migration.
-- MigrationRunner verifies checksums and refuses to start on drift.
--
-- ADR-005: everything here is authoritative. Neo4j holds a derived projection of
-- the same information and can be rebuilt from `episodes` at any time.
--
-- ADR-011: every instant is `timestamptz`. Facts additionally carry the IANA zone
-- that was active when the underlying time phrase was uttered, because day-boundary
-- arithmetic for "last Tuesday" must run in that zone and not in UTC.
--
-- The two time axes (see `facts` below) are the structural heart of this schema.

-- ------------------------------------------------------------------- entities

CREATE TABLE IF NOT EXISTS entities (
    id              UUID        PRIMARY KEY,
    name            TEXT        NOT NULL,
    entity_type     TEXT        NOT NULL,
    is_provisional  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL,
    merged_into     UUID        REFERENCES entities (id) ON DELETE RESTRICT,
    merged_at       TIMESTAMPTZ,
    merge_reason    TEXT,
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT entities_type_check CHECK (
        entity_type IN ('person', 'organization', 'place', 'project', 'other')
    ),
    -- merged_into and merged_at are set together or not at all. A merge target
    -- without a timestamp would make the operation unauditable and therefore
    -- irreversible, which ADR-014 forbids.
    CONSTRAINT entities_merge_is_consistent CHECK (
        (merged_into IS NULL) = (merged_at IS NULL)
    ),
    CONSTRAINT entities_no_self_merge CHECK (merged_into IS DISTINCT FROM id)
);

COMMENT ON COLUMN entities.is_provisional IS
    'TRUE when created from an ambiguous mention (ADR-014). Never merged automatically; surfaced for deliberate review.';
COMMENT ON COLUMN entities.merged_into IS
    'Set by an explicit merge. The absorbed row is retained rather than deleted so the merge stays reversible via memory_operations.';

-- Entity resolution looks up by lowercased name, so the index must match.
CREATE INDEX IF NOT EXISTS entities_name_lower_idx
    ON entities (lower(name))
    WHERE deleted_at IS NULL AND merged_into IS NULL;

CREATE INDEX IF NOT EXISTS entities_provisional_idx
    ON entities (created_at DESC)
    WHERE is_provisional AND deleted_at IS NULL AND merged_into IS NULL;

CREATE TABLE IF NOT EXISTS entity_aliases (
    entity_id   UUID NOT NULL REFERENCES entities (id) ON DELETE CASCADE,
    alias       TEXT NOT NULL,
    PRIMARY KEY (entity_id, alias)
);

CREATE INDEX IF NOT EXISTS entity_aliases_lower_idx ON entity_aliases (lower(alias));

-- ---------------------------------------------------------------------- facts
--
-- TWO INDEPENDENT TIME AXES. Conflating them is how a temporal memory system
-- starts giving confidently wrong answers.
--
--   valid_from / valid_to      when the fact was true IN THE WORLD
--   asserted_at / retracted_at when THE SYSTEM BELIEVED it
--
-- "What was true in March?"          reads the first pair.
-- "What did I think was true in March?" reads the second.
--
-- Those are different questions with different answers (FR-04.5 and FR-05.5), and
-- satisfying both simultaneously is only possible while the axes stay separate.

CREATE TABLE IF NOT EXISTS facts (
    id                      UUID        PRIMARY KEY,
    statement               TEXT        NOT NULL,
    origin                  TEXT        NOT NULL,
    confidence              TEXT        NOT NULL,
    salience                REAL        NOT NULL DEFAULT 0,
    salience_category       TEXT,

    -- world time
    valid_from              TIMESTAMPTZ,
    valid_to                TIMESTAMPTZ,

    -- belief time
    asserted_at             TIMESTAMPTZ NOT NULL,
    retracted_at            TIMESTAMPTZ,

    -- the original time phrase, never discarded (ADR-010)
    temporal_raw_phrase     TEXT,
    temporal_granularity    TEXT,
    temporal_method         TEXT,
    temporal_anchor_zone    TEXT,

    superseded_by           UUID        REFERENCES facts (id) ON DELETE RESTRICT,
    created_at              TIMESTAMPTZ NOT NULL,

    CONSTRAINT facts_origin_check CHECK (
        origin IN ('user_stated', 'ai_inferred', 'imported')
    ),
    CONSTRAINT facts_confidence_check CHECK (
        confidence IN ('certain', 'probable', 'uncertain')
    ),
    CONSTRAINT facts_salience_range CHECK (salience >= 0 AND salience <= 1),
    CONSTRAINT facts_world_time_ordered CHECK (
        valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from
    ),
    CONSTRAINT facts_belief_time_ordered CHECK (
        retracted_at IS NULL OR retracted_at >= asserted_at
    ),
    -- ADR-010: an unresolvable phrase must never carry a fabricated date. A
    -- plausible-looking wrong date is indistinguishable from a real one once stored.
    CONSTRAINT facts_unknown_granularity_has_no_dates CHECK (
        temporal_granularity IS DISTINCT FROM 'unknown'
        OR (valid_from IS NULL AND valid_to IS NULL)
    ),
    CONSTRAINT facts_no_self_supersede CHECK (superseded_by IS DISTINCT FROM id)
);

COMMENT ON COLUMN facts.origin IS
    'Set once at creation and never changed. FR-02.7: an AI inference must never become a user-stated fact. There is deliberately no operation anywhere that mutates this.';
COMMENT ON COLUMN facts.salience IS
    'ADR-017. Weights retrieval ranking; never filters. Aggressive extraction (FR-02.2) means the failure mode is burying signal in trivia, not forgetting.';

CREATE INDEX IF NOT EXISTS facts_active_salience_idx
    ON facts (salience DESC, created_at DESC)
    WHERE retracted_at IS NULL AND superseded_by IS NULL;

CREATE INDEX IF NOT EXISTS facts_world_time_idx ON facts (valid_from, valid_to);
CREATE INDEX IF NOT EXISTS facts_belief_time_idx ON facts (asserted_at, retracted_at);

CREATE TABLE IF NOT EXISTS fact_subjects (
    fact_id     UUID NOT NULL REFERENCES facts (id) ON DELETE CASCADE,
    entity_id   UUID NOT NULL REFERENCES entities (id) ON DELETE RESTRICT,
    PRIMARY KEY (fact_id, entity_id)
);

CREATE INDEX IF NOT EXISTS fact_subjects_entity_idx ON fact_subjects (entity_id);

-- --------------------------------------------------------------------- events

CREATE TABLE IF NOT EXISTS events (
    id                      UUID        PRIMARY KEY,
    description             TEXT        NOT NULL,
    origin                  TEXT        NOT NULL,
    salience                REAL        NOT NULL DEFAULT 0,
    salience_category       TEXT,
    occurred_at             TIMESTAMPTZ,
    occurred_through        TIMESTAMPTZ,
    temporal_raw_phrase     TEXT,
    temporal_granularity    TEXT,
    temporal_method         TEXT,
    temporal_anchor_zone    TEXT,
    retracted_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL,
    CONSTRAINT events_origin_check CHECK (
        origin IN ('user_stated', 'ai_inferred', 'imported')
    ),
    CONSTRAINT events_salience_range CHECK (salience >= 0 AND salience <= 1),
    CONSTRAINT events_time_ordered CHECK (
        occurred_at IS NULL OR occurred_through IS NULL OR occurred_through >= occurred_at
    ),
    CONSTRAINT events_unknown_granularity_has_no_dates CHECK (
        temporal_granularity IS DISTINCT FROM 'unknown'
        OR (occurred_at IS NULL AND occurred_through IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS events_occurred_at_idx ON events (occurred_at);

CREATE TABLE IF NOT EXISTS event_participants (
    event_id    UUID NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    entity_id   UUID NOT NULL REFERENCES entities (id) ON DELETE RESTRICT,
    PRIMARY KEY (event_id, entity_id)
);

CREATE INDEX IF NOT EXISTS event_participants_entity_idx ON event_participants (entity_id);

-- -------------------------------------------------------------- relationships

CREATE TABLE IF NOT EXISTS relationships (
    id              UUID        PRIMARY KEY,
    from_entity_id  UUID        NOT NULL REFERENCES entities (id) ON DELETE RESTRICT,
    to_entity_id    UUID        NOT NULL REFERENCES entities (id) ON DELETE RESTRICT,
    relation_type   TEXT        NOT NULL,
    origin          TEXT        NOT NULL,
    valid_from      TIMESTAMPTZ,
    valid_to        TIMESTAMPTZ,
    retracted_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT relationships_origin_check CHECK (
        origin IN ('user_stated', 'ai_inferred', 'imported')
    ),
    CONSTRAINT relationships_time_ordered CHECK (
        valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from
    ),
    CONSTRAINT relationships_no_self_link CHECK (from_entity_id <> to_entity_id)
);

CREATE INDEX IF NOT EXISTS relationships_from_idx ON relationships (from_entity_id);
CREATE INDEX IF NOT EXISTS relationships_to_idx ON relationships (to_entity_id);

-- ---------------------------------------------------------- provenance index
--
-- Many-to-many from a memory record to the episodes that support it.
--
-- This table is what makes the corroboration rule in ADR-012 implementable: when a
-- source is deleted, a fact is retracted ONLY IF that was its last supporting
-- episode. A single provenance column could not express "supported by three
-- conversations", and deleting one of them would then either orphan the fact or
-- destroy knowledge that still has evidence.

CREATE TABLE IF NOT EXISTS provenance_index (
    memory_id       UUID        NOT NULL,
    memory_kind     TEXT        NOT NULL,
    episode_id      UUID        NOT NULL REFERENCES episodes (id) ON DELETE RESTRICT,
    conversation_id UUID        REFERENCES conversations (id) ON DELETE RESTRICT,
    message_id      UUID        REFERENCES messages (id) ON DELETE RESTRICT,
    document_id     UUID,
    recorded_at     TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (memory_id, memory_kind, episode_id),
    CONSTRAINT provenance_kind_check CHECK (
        memory_kind IN ('fact', 'event', 'relationship', 'entity')
    )
);

COMMENT ON TABLE provenance_index IS
    'FR-02.5. Many-to-many by design so the ADR-012 corroboration rule can count remaining sources before retracting.';

CREATE INDEX IF NOT EXISTS provenance_memory_idx ON provenance_index (memory_id, memory_kind);
CREATE INDEX IF NOT EXISTS provenance_episode_idx ON provenance_index (episode_id);
CREATE INDEX IF NOT EXISTS provenance_conversation_idx ON provenance_index (conversation_id);
